on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      name: login check
      steps:
        - uses: actions/checkout@v3
        - name: Azure Login 
          if: always() 
          uses: azure/login@v1 
          with:
            client-id : ${{ secrets.TF_ARM_AZURE_CLIENT_ID }}
            #clientSecret: ${{ secrets.TF_ARM_CLIENT_SECRET }}
            subscription-id: ${{ secrets.TF_ARM_AZURE_SUBSCRIPTION_ID }}
            tenant-id: ${{ secrets.TF_ARM_AZURE_TENANT_ID }}
            
            #'creds', '', '', ''
            #creds: ${{secrets.TF_ARM_CLIENT_ID},{secrets.TF_ARM_CLIENT_SECRET},{secrets.TF_ARM_SUBSCRIPTION_ID},{secrets.TF_ARM_TENANT_ID}}
        #- name: concat-json
         # id: concat-json
          #run: >
           # Azure_Credentials='{"clientId":"'${{ secrets.TF_ARM_CLIENT_ID}}'","clientSecret":"'${{secrets.TF_ARM_CLIENT_SECRET}}'","subscriptionId":"'${{secrets.TF_ARM_SUBSCRIPTION_ID}}'","tenantId":"'${{secrets.TF_ARM_TENANT_ID}}'","activeDirectoryEndpointUrl":"https://login.microsoftonline.com","resourceManagerEndpointUrl":"https://management.azure.com/","activeDirectoryGraphResourceId":"https://graph.windows.net/","sqlManagementEndpointUrl":"https://management.core.windows.net:8443/","galleryEndpointUrl":"https://gallery.azure.com/","managementEndpointUrl":"https://management.core.windows.net/"}'
            #echo "::set-output name=Azure_Credentials::$Azure_Credentials"
            

