on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'This deploys to QA'
    steps:
    - uses: actions/checkout@v3
    
    - name: concat-json
        id: concat-json
        run: |
          Azure_Credentials='{"clientId":"'${{ secrets.TF_ARM_CLIENT_ID }}'","clientSecret":"'${{ secrets.TF_ARM_CLIENT_SECRET}}'","subscriptionId":"'${{ secrets.TF_ARM_SUBSCRIPTION_ID}}'","tenantId":"'${{ secrets.TF_ARM_TENANT_ID}}'","activeDirectoryEndpointUrl":"https://login.microsoftonline.com","resourceManagerEndpointUrl":"https://management.azure.com/","activeDirectoryGraphResourceId":"https://graph.windows.net/","sqlManagementEndpointUrl":"https://management.core.windows.net:8443/","galleryEndpointUrl":"https://gallery.azure.com/","managementEndpointUrl":"https://management.core.windows.net/"}'
          echo "::set-output name=Azure_Credentials::$Azure_Credentials"
        # login using the created credentials
        - name: Azure Login
        if: always() 
        uses: azure/login@v1
        with:
          creds: ${{ steps.concat-json.outputs.Azure_Credentials }}
